INTENT_PROTOTYPES = {
    "TRIGGER_PROPERTY_UI": [
        "create a new property",
        "list my apartment",
        "publish a listing",
        "add a new house",
        "I want to list my property",
        "put my flat up for rent",
        "add a property to the platform",
        "start listing a new place",
    ],
    "TRIGGER_DASHBOARD_UI": [
        "view my tours",
        "see my applications",
        "view my properties",
        "my dashboard",
        "check my listings",
        "my bookings",
        "view tours",
        "take me to my dashboard",
        "show me my account overview",
        "what's happening with my listings",
    ],
    # Payment and KYC are split by READ vs WRITE, not by topic:
    # - Read-only checks (balance, verification status) stay answerable in
    #   chat via payment-specialist/kyc-specialist below, since the agent
    #   can just call get_wallet_balance_worker / get_kyc_status_worker
    #   and report back — no form input needed.
    # - Actions that require entering info chat can't collect (card/bank
    #   details, government ID uploads) redirect to the real UI here.
    "TRIGGER_PAYMENT_UI": [
        "pay my rent now",
        "I want to make a payment",
        "pay rent",
        "I need to pay rent",
        "transfer money",
        "send a payment",
        "process a rent payment",
        "open the payments page",
        "take me to checkout",
        "take me to the payment screen",
        "I want to pay",
    ],
    "TRIGGER_KYC_UI": [
        "verify my identity",
        "I want to verify my identity",
        "upload my ID",
        "submit my documents",
        "open identity verification",
        "take me to KYC",
        "complete my verification",
        "go to the verification page",
        "start my identity verification",
    ],
    "property-specialist": [
        "search for houses",
        "find an apartment",
        "show me listings",
        "3 bedroom apartment in Lekki",
        "find me a flat under 2 million",
        "what properties do you have in Abuja",
        "looking for a place to rent",
        "any houses available near Unilag",
        "show me 2 bedroom flats",
    ],
    "tour-specialist": [
        "book a tour",
        "schedule a visit",
        "see the place",
        "I want to view this property in person",
        "can I come see it",
        "set up a viewing",
        "when can I visit",
        "schedule a walkthrough",
    ],
    "lease-specialist": [
        "sign lease agreement",
        "view contract terms",
        "update lease terms",
        "sign my lease",
        "view my active lease",
        "I want to apply for this property",
        "start my rental application",
        "review my tenancy agreement",
        "download my lease document",
    ],
    "payment-specialist": [
        "check my wallet balance",
        "what's my wallet balance",
        "how much money do I have",
        "show my balance",
        "what's my account balance",
        "do I have enough to pay rent",
        "how much do I have in my wallet",
    ],
    "kyc-specialist": [
        "what's my verification status",
        "am I verified yet",
        "kyc status",
        "check my verification status",
        "is my identity verified",
        "has my ID been approved",
    ],
    "chat-specialist": [
        "message landlord",
        "contact owner",
        "start a chat",
        "I want to talk to the property manager",
        "send a message to the landlord",
        "get in touch with the owner",
    ],
    "supervisor": [
        "how does this work",
        "can you explain how a lease works",
        "what are the rules here",
        "tell me about the platform",
        "hello",
        "what can you do",
        "hi there",
        "good morning",
        "what is HousePadi",
        "how do I use this app",
        "thanks",
        "who are you",
    ],
}

INTENT_UI_MAP = {
    "TRIGGER_PROPERTY_UI": "/dashboard/landlord/create-property",
    "TRIGGER_DASHBOARD_UI": "/dashboard",
    "TRIGGER_PAYMENT_UI": "/payments",
    "TRIGGER_KYC_UI": "/profile/verify",
}

INTENT_CONTENT_MAP = {
    "TRIGGER_PROPERTY_UI": "Opening the property listing form for you...",
    "TRIGGER_DASHBOARD_UI": "Opening your dashboard...",
    "TRIGGER_PAYMENT_UI": "Taking you to your payments page...",
    "TRIGGER_KYC_UI": "Opening identity verification..."
}